LANGUAGES = [ { name: 'ActionScript', ace_syntax: 'none', pygments_syntax: 'actionscript'},
                    { name: 'Ada', ace_syntax: 'none', pygments_syntax: 'ada'},
                    { name: 'Apex', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'AppleScript', ace_syntax: 'none', pygments_syntax: 'applescript'},
                    { name: 'Arc', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Arduino', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'ASP', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Assembly', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Augeas', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'AutoHotKey', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Basic', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Boo', ace_syntax: 'none', pygments_syntax: 'boo'},
                    { name: 'Bro', ace_syntax: 'none', pygments_syntax: 'bro'},
                    { name: 'C', ace_syntax: 'c_cpp', pygments_syntax: 'c'},
                    { name: 'C#', ace_syntax: 'csharp', pygments_syntax: 'csharp'},
                    { name: 'C++', ace_syntax: 'c_cpp', pygments_syntax: 'cpp'},
                    { name: 'Ceylon', ace_syntax: 'none', pygments_syntax: 'ceylon'},
                    { name: 'Clojure', ace_syntax: 'clojure', pygments_syntax: 'clojure'},
                    { name: 'CoffeeScript', ace_syntax: 'coffee', pygments_syntax: 'coffeescript'},
                    { name: 'ColdFusion', ace_syntax: 'coldfusion', pygments_syntax: 'coldfusion'},
                    { name: 'Common Lisp', ace_syntax: 'lisp', pygments_syntax: 'cl'},
                    { name: 'Coq', ace_syntax: 'none', pygments_syntax: 'coq'},
                    { name: 'D', ace_syntax: 'none', pygments_syntax: 'd'},
                    { name: 'Dart', ace_syntax: 'dart', pygments_syntax: 'dart'},
                    { name: 'DCPU-16 ASM', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Delphi', ace_syntax: 'none', pygments_syntax: 'delphi'},
                    { name: 'Dylan', ace_syntax: 'none', pygments_syntax: 'dylan'},
                    { name: 'eC', ace_syntax: 'none', pygments_syntax: 'ec'},
                    { name: 'Ecl', ace_syntax: 'none', pygments_syntax: 'ecl'},
                    { name: 'Eiffel', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Elixir', ace_syntax: 'none', pygments_syntax: 'elixir'},
                    { name: 'Emacs Lisp', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Erlang', ace_syntax: 'none', pygments_syntax: 'erlang'},
                    { name: 'F#', ace_syntax: 'none', pygments_syntax: 'fsharp'},
                    { name: 'Factor', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Fancy', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Fantom', ace_syntax: 'none', pygments_syntax: 'fan'},
                    { name: 'Felix', ace_syntax: 'none', pygments_syntax: 'felix'},
                    { name: 'FORTRAN 90', ace_syntax: 'none', pygments_syntax: 'fortran'},
                    { name: 'Go', ace_syntax: 'golang', pygments_syntax: 'go'},
                    { name: 'Gosu', ace_syntax: 'none', pygments_syntax: 'gosu'},
                    { name: 'Groovy', ace_syntax: 'groovy', pygments_syntax: 'groovy'},
                    { name: 'Haskell', ace_syntax: 'none', pygments_syntax: 'haskell'},
                    { name: 'Io', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Ioke', ace_syntax: 'none', pygments_syntax: 'ioke'},
                    { name: 'J', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Java', ace_syntax: 'java', pygments_syntax: 'java'},
                    { name: 'JavaScript', ace_syntax: 'javascript', pygments_syntax: 'javascript'},
                    { name: 'Julia', ace_syntax: 'none', pygments_syntax: 'julia'},
                    { name: 'Koka', ace_syntax: 'none', pygments_syntax: 'koka'},
                    { name: 'Kotlin', ace_syntax: 'none', pygments_syntax: 'kotlin'},
                    { name: 'Logtalk', ace_syntax: 'none', pygments_syntax: 'logtalk'},
                    { name: 'Lua', ace_syntax: 'lua', pygments_syntax: 'lua'},
                    { name: 'Matlab', ace_syntax: 'none', pygments_syntax: 'matlab'},
                    { name: 'Max', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Mirah', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Monkey', ace_syntax: 'none', pygments_syntax: 'monkey'},
                    { name: 'Nemerle', ace_syntax: 'none', pygments_syntax: 'nemerle'},
                    { name: 'Nimrod', ace_syntax: 'none', pygments_syntax: 'nimrod'},
                    { name: 'Nu', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Objective-C', ace_syntax: 'objectivec', pygments_syntax: 'objectivec'},
                    { name: 'Objective-C++', ace_syntax: 'none', pygments_syntax: 'objectivec++'},
                    { name: 'Objective-J', ace_syntax: 'none', pygments_syntax: 'objectivej'},
                    { name: 'OCaml', ace_syntax: 'ocaml', pygments_syntax: 'ocaml'},
                    { name: 'Ooc', ace_syntax: 'none', pygments_syntax: 'ooc'},
                    { name: 'Opa', ace_syntax: 'none', pygments_syntax: 'opa'},
                    { name: 'OpenEdge ABL', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Parrot', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Perl', ace_syntax: 'perl', pygments_syntax: 'perl'},
                    { name: 'PHP', ace_syntax: 'php', pygments_syntax: 'php'},
                    { name: 'Prolog', ace_syntax: 'none', pygments_syntax: 'prolog'},
                    { name: 'Puppet', ace_syntax: 'none', pygments_syntax: 'puppet'},
                    { name: 'Pure Data', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Python', ace_syntax: 'python', pygments_syntax: 'python'},
                    { name: 'Python 3', ace_syntax: 'python', pygments_syntax: 'python3'},
                    { name: 'R', ace_syntax: 'r', pygments_syntax: 'r'},
                    { name: 'Racket', ace_syntax: 'none', pygments_syntax: 'racket'},
                    { name: 'Rebol', ace_syntax: 'none', pygments_syntax: 'rebol'},
                    { name: 'Ruby', ace_syntax: 'ruby', pygments_syntax: 'ruby'},
                    { name: 'Rust', ace_syntax: 'none', pygments_syntax: 'rust'},
                    { name: 'Scala', ace_syntax: 'scala', pygments_syntax: 'scala'},
                    { name: 'Scheme', ace_syntax: 'scheme', pygments_syntax: 'scheme'},
                    { name: 'SciLab', ace_syntax: 'none', pygments_syntax: 'scilab'},
                    { name: 'Self', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Shell', ace_syntax: 'sh', pygments_syntax: 'sh'},
                    { name: 'Smalltalk', ace_syntax: 'none', pygments_syntax: 'smalltalk'},
                    { name: 'Standard ML', ace_syntax: 'none', pygments_syntax: 'sml'},
                    { name: 'SuperCollider', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Text', ace_syntax: 'text', pygments_syntax: 'none'},
                    { name: 'Tcl', ace_syntax: 'tcl', pygments_syntax: 'tcl'},
                    { name: 'Turing', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'Vala', ace_syntax: 'none', pygments_syntax: 'vala'},
                    { name: 'Verilog', ace_syntax: 'none', pygments_syntax: 'v'},
                    { name: 'VHDL', ace_syntax: 'none', pygments_syntax: 'vhdl'},
                    { name: 'VimL', ace_syntax: 'none', pygments_syntax: 'vim'},
                    { name: 'Visual Basic', ace_syntax: 'none', pygments_syntax: 'none'},
                    { name: 'XQuery', ace_syntax: 'xquery', pygments_syntax: 'xquery'}]
