# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' , syntax_highlighting: 'none'}, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Language.create!([{ name: 'ActionScript', syntax_highlighting: 'none'},
                 { name: 'Ada', syntax_highlighting: 'none'},
                 { name: 'Apex', syntax_highlighting: 'none'},
                 { name: 'AppleScript', syntax_highlighting: 'none'},
                 { name: 'Arc', syntax_highlighting: 'none'},
                 { name: 'Arduino', syntax_highlighting: 'none'},
                 { name: 'ASP', syntax_highlighting: 'none'},
                 { name: 'Assembly', syntax_highlighting: 'none'},
                 { name: 'Augeas', syntax_highlighting: 'none'},
                 { name: 'AutoHotKey', syntax_highlighting: 'none'},
                 { name: 'Boo', syntax_highlighting: 'none'},
                 { name: 'Bro', syntax_highlighting: 'none'},
                 { name: 'C', syntax_highlighting: 'c_cpp'},
                 { name: 'C#', syntax_highlighting: 'csharp'},
                 { name: 'C++', syntax_highlighting: 'c_cpp'},
                 { name: 'Ceylon', syntax_highlighting: 'none'},
                 { name: 'Clojure', syntax_highlighting: 'clojure'},
                 { name: 'CoffeeScript', syntax_highlighting: 'coffee'},
                 { name: 'ColdFusion', syntax_highlighting: 'coldfusion'},
                 { name: 'Common Lisp', syntax_highlighting: 'lisp'},
                 { name: 'Coq', syntax_highlighting: 'none'},
                 { name: 'D', syntax_highlighting: 'none'},
                 { name: 'Dart', syntax_highlighting: 'dart'},
                 { name: 'DCPU-16 ASM', syntax_highlighting: 'none'},
                 { name: 'Delphi', syntax_highlighting: 'none'},
                 { name: 'Dylan', syntax_highlighting: 'none'},
                 { name: 'eC', syntax_highlighting: 'none'},
                 { name: 'Ecl', syntax_highlighting: 'none'},
                 { name: 'Eiffel', syntax_highlighting: 'none'},
                 { name: 'Elixir', syntax_highlighting: 'none'},
                 { name: 'Emacs Lisp', syntax_highlighting: 'none'},
                 { name: 'Erlang', syntax_highlighting: 'none'},
                 { name: 'F#', syntax_highlighting: 'none'},
                 { name: 'Factor', syntax_highlighting: 'none'},
                 { name: 'Fancy', syntax_highlighting: 'none'},
                 { name: 'Fantom', syntax_highlighting: 'none'},
                 { name: 'FORTRAN', syntax_highlighting: 'none'},
                 { name: 'Go', syntax_highlighting: 'golang'},
                 { name: 'Gosu', syntax_highlighting: 'none'},
                 { name: 'Groovy', syntax_highlighting: 'groovy'},
                 { name: 'Haskell', syntax_highlighting: 'none'},
                 { name: 'Io', syntax_highlighting: 'none'},
                 { name: 'Ioke', syntax_highlighting: 'none'},
                 { name: 'Java', syntax_highlighting: 'java'},
                 { name: 'JavaScript', syntax_highlighting: 'javascript'},
                 { name: 'Julia', syntax_highlighting: 'none'},
                 { name: 'Kotlin', syntax_highlighting: 'none'},
                 { name: 'Logtalk', syntax_highlighting: 'none'},
                 { name: 'Lua', syntax_highlighting: 'lua'},
                 { name: 'Matlab', syntax_highlighting: 'none'},
                 { name: 'Max', syntax_highlighting: 'none'},
                 { name: 'Mirah', syntax_highlighting: 'none'},
                 { name: 'Nemerle', syntax_highlighting: 'none'},
                 { name: 'Nimrod', syntax_highlighting: 'none'},
                 { name: 'Nu', syntax_highlighting: 'none'},
                 { name: 'Objective-C', syntax_highlighting: 'objectivec'},
                 { name: 'Objective-J', syntax_highlighting: 'none'},
                 { name: 'OCaml', syntax_highlighting: 'ocaml'},
                 { name: 'ooc', syntax_highlighting: 'none'},
                 { name: 'Opa', syntax_highlighting: 'none'},
                 { name: 'OpenEdge ABL', syntax_highlighting: 'none'},
                 { name: 'Parrot', syntax_highlighting: 'none'},
                 { name: 'Perl', syntax_highlighting: 'perl'},
                 { name: 'PHP', syntax_highlighting: 'none'},
                 { name: 'Prolog', syntax_highlighting: 'none'},
                 { name: 'Puppet', syntax_highlighting: 'none'},
                 { name: 'Pure Data', syntax_highlighting: 'none'},
                 { name: 'Python', syntax_highlighting: 'python'},
                 { name: 'R', syntax_highlighting: 'r'},
                 { name: 'Racket', syntax_highlighting: 'none'},
                 { name: 'Rebol', syntax_highlighting: 'none'},
                 { name: 'Ruby', syntax_highlighting: 'ruby'},
                 { name: 'Rust', syntax_highlighting: 'none'},
                 { name: 'Scala', syntax_highlighting: 'scala'},
                 { name: 'Scheme', syntax_highlighting: 'scheme'},
                 { name: 'SciLab', syntax_highlighting: 'none'},
                 { name: 'Self', syntax_highlighting: 'none'},
                 { name: 'Shell', syntax_highlighting: 'sh'},
                 { name: 'Smalltalk', syntax_highlighting: 'none'},
                 { name: 'Standard ML', syntax_highlighting: 'none'},
                 { name: 'SuperColider', syntax_highlighting: 'none'},
                 { name: 'Tcl', syntax_highlighting: 'tcl'},
                 { name: 'Turing', syntax_highlighting: 'none'},
                 { name: 'Vala', syntax_highlighting: 'none'},
                 { name: 'Verilog', syntax_highlighting: 'none'},
                 { name: 'VHDL', syntax_highlighting: 'none'},
                 { name: 'VimL', syntax_highlighting: 'none'},
                 { name: 'Visual Basic', syntax_highlighting: 'none'},
                 { name: 'XQuery', syntax_highlighting: 'xquery'}])
