# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Language.create([{ name: 'ActionScript'},
                 { name: 'Ada'},
                 { name: 'Apex'},
                 { name: 'AppleScript'},
                 { name: 'Arc'},
                 { name: 'Arduino'},
                 { name: 'ASP'},
                 { name: 'Assembly'},
                 { name: 'Augeas'},
                 { name: 'AutoHotKey'},
                 { name: 'Boo'},
                 { name: 'Bro'},
                 { name: 'C'},
                 { name: 'C#'},
                 { name: 'C++'},
                 { name: 'Ceylon'},
                 { name: 'Clojure'},
                 { name: 'CoffeeScript'},
                 { name: 'ColdFusion'},
                 { name: 'Common Lisp'},
                 { name: 'Coq'},
                 { name: 'D'},
                 { name: 'Dart'},
                 { name: 'DCPU-16 ASM'},
                 { name: 'Delphi'},
                 { name: 'Dylan'},
                 { name: 'eC'},
                 { name: 'Ecl'},
                 { name: 'Eiffel'},
                 { name: 'Elixir'},
                 { name: 'Emacs Lisp'},
                 { name: 'Erlang'},
                 { name: 'F#'},
                 { name: 'Factor'},
                 { name: 'Fancy'},
                 { name: 'Fantom'},
                 { name: 'FORTRAN'},
                 { name: 'Go'},
                 { name: 'Gosu'},
                 { name: 'Groovy'},
                 { name: 'Haskell'},
                 { name: 'Io'},
                 { name: 'Ioke'},
                 { name: 'Java'},
                 { name: 'JavaScript'},
                 { name: 'Julia'},
                 { name: 'Kotlin'},
                 { name: 'Logtalk'},
                 { name: 'Lua'},
                 { name: 'Matlab'},
                 { name: 'Max'},
                 { name: 'Mirah'},
                 { name: 'Nemerle'},
                 { name: 'Nimrod'},
                 { name: 'Nu'},
                 { name: 'Objective-C'},
                 { name: 'Objective-J'},
                 { name: 'OCaml'},
                 { name: 'ooc'},
                 { name: 'Opa'},
                 { name: 'OpenEdge ABL'},
                 { name: 'Parrot'},
                 { name: 'Perl'},
                 { name: 'PHP'},
                 { name:'Prolog'},
                 { name: 'Puppet'},
                 { name: 'Pure Data'},
                 { name: 'Python'},
                 { name: 'R'},
                 { name: 'Racket'},
                 { name: 'Rebol'},
                 { name: 'Ruby'},
                 { name: 'Rust'},
                 { name: 'Scala'},
                 { name: 'Scheme'},
                 { name: 'SciLab'},
                 { name: 'Self'},
                 { name: 'Shell'},
                 { name: 'Smalltalk'},
                 { name: 'Standard ML'},
                 { name: 'SuperColider'},
                 { name: 'Tcl'},
                 { name: 'Turing'},
                 { name: 'Vala'},
                 { name: 'Verilog'},
                 { name: 'VHDL'},
                 { name: 'VHDL'},
                 { name: 'VimL'},
                 { name: 'Visual Basic'},
                 { name: 'XQuery'}])
